-- Migration 039: New document types
-- Adds document types required for the local/foreign/farmer statutory split
-- and for the updated category certification groups.

ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'CR5';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ID_PASSPORT_COPY';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'OFFER_LETTER_TITLE_DEEDS';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'DIRECTORS_LIST';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'PHYSICAL_ADDRESS_PROOF';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'TAX_COMPLIANCE_FOREIGN';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'RENEWABLE_ENERGY_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'LICENSED_ELECTRICIAN_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'LICENSED_PLUMBER_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'TRANSPORT_OPERATORS_LICENSE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ROADWORTHINESS_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'REGISTERED_SECURITY_LICENSE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'PEST_CONTROL_CHEMICAL_LICENSE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ENVIRONMENTAL_LICENSE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'IRATA_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'WORKING_AT_HEIGHTS_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'PUBLIC_LIABILITY_INSURANCE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'MATERIAL_SAFETY_DATA_SHEETS';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'CE_SABS_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'OEKO_TEX_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'GOTS_BCI_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ISO_27001';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'VETERINARY_HEALTH_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'NSSA_COMPLIANCE';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'HACCP';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'FSSC_22000';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ISO_22000';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'GLOBAL_GAP_CERT';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ISO_9001_PRODUCT_WARRANTY';
ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'ECO_LANDSCAPING_CERT';
